language: cpp
dist: xenial

matrix:
  fast_finish: true
  include:
    - os: linux
      name: "Compiler GCC 6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - zstd
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      name: "Compiler GCC 7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - zstd
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      name: "Compiler GCC 8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - zstd
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      name: "Compiler GCC 9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - zstd
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: windows
      name: "Compiler MSVC"
         
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -j 6
  - ctest -C Debug --verbose